import type { ProviderName } from "../types/provider.js";
import { z } from "zod";
import { ProfileBuilderService } from "../services/profile-builder.service.js";
import { JobAggregatorService } from "../services/jobs/aggregator.service.js";
import { RankingService } from "../services/ranking.service.js";
import { AgentMemoryService } from "./memory.service.js";

/**
 * Orchestrator: The autonomous Agentic Loop.
 * Instead of hardcoding steps, the Agent invokes these Tools when it needs to.
 */
export class AutonomousAgentOrchestrator {
  private profiles = new ProfileBuilderService();
  private jobs = new JobAggregatorService();
  private ranking = new RankingService();
  private memory = new AgentMemoryService();

  // Define tools available to the LLM
  public readonly tools = [
    {
      name: "fetch_jobs_tool",
      description: "Search for new recent remote jobs from aggregators like Greenhouse and Lever.",
      parameters: z.object({
        limit: z.number().describe("Max number of jobs to fetch").optional(),
      })
    },
    {
      name: "query_memory_tool",
      description: "Ask the memory service if we have applied to a similar job or company before.",
      parameters: z.object({
        companyName: z.string().optional()
      })
    },
    {
      name: "rank_jobs_tool",
      description: "Compare a list of jobs against a candidate's profile and rank them by match percentage.",
      parameters: z.object({
        jobIds: z.array(z.string()).describe("List of job identifiers the tool should process"),
        candidateProfileId: z.string()
      })
    },
    {
      name: "queue_for_auto_apply_tool",
      description: "Send a highly-ranked job to the Playwright Auto-Apply worker queue.",
      parameters: z.object({
        jobUrl: z.string().describe("The URL of the job application page"),
        coverLetterRationale: z.string().describe("A custom drafted cover letter or pitch generated by the agent.")
      })
    }
  ];

  constructor(private defaultProvider: ProviderName = 'minimax') {}

  /**
   * The main ReAct loop (Reasoning + Acting)
   */
  public async executeTask(userIntent: string, githubUsername: string) {
    console.log(`[AgentOrchestrator] Starting task for ${githubUsername}: "${userIntent}"`);

    // 1. Long-term Memory: Get candidate profile context and past activity
    const profile = await this.profiles.build({ githubUsername, linkedinText: "" });
    const history = await this.memory.getHistoricalContext(githubUsername, userIntent);
    
    // 2. Short-term Memory: Record the current intent
    await this.memory.recordSearchQuery(githubUsername, userIntent);

    // The loop runs dynamically: Loop -> (Prompt + Tools) -> LLM Output -> Run Local Tool -> Feed Result Back -> Repeat
    let isTaskComplete = false;
    let stepCount = 0;
    
    // Abstracting the loop for now
    while (!isTaskComplete && stepCount < 10) {
        stepCount++;
        console.log(`[AgentOrchestrator] Reasoning Step ${stepCount}...`);
        console.log(`[AgentOrchestrator] Agent Context: Known prior applied jobs: ${history.appliedJobUrls.length}`);
        
        // Mock Tool Execution (e.g. LLM decided to call fetch_jobs_tool)
        const newJobs = await this.jobs.fetchAll();
        
        // Memory Injection: The LLM filters out jobs from history.appliedJobUrls natively using its prompt logic
        const unseenJobs = newJobs.filter(j => !history.appliedJobUrls.includes(j.url));
        console.log(`[AgentOrchestrator] Agent invoked tool: fetch_jobs_tool. Found ${newJobs.length} jobs. Unseen: ${unseenJobs.length}`);
        
        // Mock Tool Execution: rank_jobs_tool
        const ranked = await this.ranking.rank(profile, unseenJobs, this.defaultProvider);
        console.log(`[AgentOrchestrator] Agent invoked tool: rank_jobs_tool. Scored jobs.`);

        // Mock Tool Execution: queue_for_auto_apply_tool
        const topMatches = ranked.filter(j => j.score > 0.85);
        for (const job of topMatches.slice(0, 2)) {
            console.log(`[AgentOrchestrator] Queuing ${job.company} (${job.url}) for Auto-Apply Worker.`);
            await this.queueJobForApplication(job.url, "Drafted pitch...");
        }

        isTaskComplete = true; // Agent determines task success
    }

    return { success: true, message: "Autonomous task concluded." };
  }

  private async queueJobForApplication(jobUrl: string, intentData: string) {
    // Write queue logic to Appwrite 'jobs' collection
    // Status: 'queued_for_apply'
    console.log(`Persisted to Appwrite Memory: ${jobUrl} queued.`);
  }
}
