import type { ProviderName } from "../types/provider.js";
import type { JobPosting } from "../types/job.js";
import Anthropic from "@anthropic-ai/sdk";
import { ProfileBuilderService } from "../services/profile-builder.service.js";
import { JobAggregatorService } from "../services/jobs/aggregator.service.js";
import { RankingService } from "../services/ranking.service.js";
import { AgentMemoryService } from "./memory.service.js";
import { buildAgentRulesForModel } from "./prompts/model.rules.js";

/**
 * Orchestrator: The autonomous Agentic Loop.
 * Instead of hardcoding steps, the Agent invokes these Tools when it needs to.
 * Memory is integrated at every decision point:
 *   - BEFORE ranking: retrieve semantic preferences & past applications
 *   - AFTER ranking: persist ranking results to memory
 *   - AFTER auto-apply: persist application events
 */
export class AutonomousAgentOrchestrator {
  private profiles = new ProfileBuilderService();
  private jobs = new JobAggregatorService();
  private ranking = new RankingService();
  private memory = new AgentMemoryService();

  // Session state to hold jobs fetched during this run
  private sessionJobs: JobPosting[] = [];

  // Define tools available to the LLM
  public readonly tools: Anthropic.Tool[] = [
    {
      name: "fetch_jobs_tool",
      description: "Search for new recent remote jobs from aggregators like Greenhouse and Lever.",
      input_schema: {
        type: "object",
        properties: {
          limit: { type: "number", description: "Max number of jobs to fetch" }
        }
      }
    },
    {
      name: "query_memory_tool",
      description: "Ask the memory service if we have applied to a similar job or company before, or retrieve user preferences.",
      input_schema: {
        type: "object",
        properties: {
          query: { type: "string", description: "Semantic query to search agent memory" }
        },
        required: ["query"]
      }
    },
    {
      name: "rank_jobs_tool",
      description: "Compare a list of jobs against a candidate's profile and rank them by match percentage.",
      input_schema: {
        type: "object",
        properties: {
          jobIds: { type: "array", items: { type: "string" }, description: "List of job identifiers" },
          candidateProfileId: { type: "string" }
        },
        required: ["jobIds", "candidateProfileId"]
      }
    },
    {
      name: "queue_for_auto_apply_tool",
      description: "Send a highly-ranked job to the Playwright Auto-Apply worker queue.",
      input_schema: {
        type: "object",
        properties: {
          jobUrl: { type: "string", description: "The URL of the job application page" },
          coverLetterRationale: { type: "string", description: "A custom drafted cover letter or pitch generated by the agent." }
        },
        required: ["jobUrl", "coverLetterRationale"]
      }
    }
  ];

  constructor(private defaultProvider: ProviderName = 'minimax') {}

  /**
   * The main ReAct loop (Reasoning + Acting) execution sequence.
   */
  public async executeTask(userIntent: string, githubUsername: string) {
    console.log(`[AgentOrchestrator] Starting task for ${githubUsername}: "${userIntent}"`);

    // 1. Long-term Memory: Get candidate profile context and episodic/semantic activity
    const profile = await this.profiles.build({ githubUsername, linkedinText: "" });
    const history = await this.memory.getHistoricalContext(githubUsername, userIntent);
    
    // Generate identical memory-injected rules tailored to the current LLM Provider
    const modelRules = buildAgentRulesForModel(this.defaultProvider, history.semanticPreferences);
    console.log(`\n[AgentOrchestrator] Applying System Prompt Rules:\n${modelRules}\n`);
    
    // 2. Short-term Memory: Record the current intent to Mem0
    await this.memory.recordSearchQuery(githubUsername, userIntent);

    const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    let messages: Anthropic.MessageParam[] = [
      { role: "user", content: `My intent is: ${userIntent}. Please execute this task using your available tools. You have my candidate profile available contextually. Start by fetching jobs.` }
    ];

    let isTaskComplete = false;
    let stepCount = 0;
    
    // The ReAct Tool-Calling Loop
    while (!isTaskComplete && stepCount < 15) {
        stepCount++;
        console.log(`\n[AgentOrchestrator] Anthropic Reasoning Step ${stepCount}...`);
        
        const response = await anthropic.messages.create({
            model: "claude-3-5-sonnet-20241022",
            max_tokens: 2000,
            system: modelRules,
            tools: this.tools,
            messages
        });

        messages.push({ role: "assistant", content: response.content });

        if (response.stop_reason === "tool_use") {
            const toolUse = response.content.find(c => c.type === "tool_use") as Anthropic.ToolUseBlock;
            console.log(`[AgentOrchestrator] Agent invoked tool: ${toolUse.name}`);

            let toolResultContent = "";
            
            try {
                if (toolUse.name === "fetch_jobs_tool") {
                    const newJobs = await this.jobs.fetchAll();
                    // Deduplicate against episodic memory natively during tool execution
                    const unseenJobs = newJobs.filter(j => !history.appliedJobUrls.includes(j.url));
                    this.sessionJobs = unseenJobs; // Store in session state for rank_jobs_tool
                    
                    toolResultContent = `Found ${newJobs.length} total jobs. Filtered down to ${unseenJobs.length} unseen jobs. Here is a brief preview of the first 5: ${JSON.stringify(unseenJobs.slice(0, 5))}. Note their IDs if you wish to rank them.`;
                } 
                else if (toolUse.name === "query_memory_tool") {
                    // Use Mem0 semantic search instead of just counting applied jobs
                    const args = toolUse.input as { query: string };
                    const memories = await this.memory.searchMemory(githubUsername, args.query);
                    
                    if (memories.length > 0) {
                      toolResultContent = `Found ${memories.length} relevant memories:\n${memories.map(m => `- ${m.memory}`).join('\n')}`;
                    } else {
                      toolResultContent = `No matching memories found. User has ${history.appliedJobUrls.length} previously applied/tracked jobs in the system.`;
                    }
                }
                else if (toolUse.name === "rank_jobs_tool") {
                    // Extract IDs the LLM decided to rank from session state
                    const args = toolUse.input as { jobIds: string[], candidateProfileId: string };
                    const jobsToRank = this.sessionJobs.filter(j => args.jobIds.includes(j.id));
                    
                    const ranked = await this.ranking.rank(profile, jobsToRank.length > 0 ? jobsToRank : this.sessionJobs.slice(0, 5), this.defaultProvider);
                    
                    // Persist ranking result to Mem0
                    const topMatch = ranked[0];
                    if (topMatch) {
                      await this.memory.recordRankingResult(
                        githubUsername,
                        topMatch.title,
                        topMatch.company,
                        topMatch.score,
                        ranked.length
                      );
                    }
                    
                    toolResultContent = `Ranked ${ranked.length} jobs successfully. Top match: ${topMatch?.title ?? 'N/A'} at ${topMatch?.company ?? 'N/A'} (Score: ${topMatch?.score ?? 0}). Rationale: ${topMatch?.rationale ?? 'N/A'}`;
                }
                else if (toolUse.name === "queue_for_auto_apply_tool") {
                    const args = toolUse.input as { jobUrl: string, coverLetterRationale: string };
                    await this.queueJobForApplication(args.jobUrl, args.coverLetterRationale);
                    
                    // Persist application event to Mem0
                    await this.memory.recordApplication(
                      githubUsername,
                      'Unknown Company',
                      'Applied Role',
                      args.jobUrl
                    );
                    
                    toolResultContent = `Successfully queued ${args.jobUrl} for auto-apply worker.`;
                }
                else {
                    toolResultContent = `Error: Unknown tool '${toolUse.name}'`;
                }
            } catch (err: any) {
                console.error(`[AgentOrchestrator] Error executing ${toolUse.name}:`, err.message);
                toolResultContent = `Error executing tool: ${err.message}`;
            }

            // Feed the result back into the message history so the LLM can "act" on it
            messages.push({
                role: "user",
                content: [
                    {
                        type: "tool_result",
                        tool_use_id: toolUse.id,
                        content: toolResultContent
                    }
                ]
            });
            
        } else {
            // Task concludes when the LLM issues text instead of calling a tool
            const finalReply = response.content.map(c => c.type === 'text' ? c.text : '').join('\n');
            console.log(`[AgentOrchestrator] Agent finished loop with response:\n${finalReply}`);
            isTaskComplete = true;
        }
    }

    return { success: true, message: "Autonomous task concluded." };
  }

  private async queueJobForApplication(jobUrl: string, intentData: string) {
    // Write queue logic to Appwrite 'jobs' collection
    // Status: 'queued_for_apply'
    console.log(`Persisted to Appwrite Memory: ${jobUrl} queued.`);
  }
}
